### ISSUE TITLE
Keyboard no appearing

### ISSUE THREAD

**Issue by Jiwei98** [MGohil/PINView.Maui#1]
Hi i downloaded your project and try before i use on mine project after i focus on the pin view my keyboard is not appearing did i set something wrong?

**Comment by MGohil** [comment]
@Jiwei98 : Would you please put on some more details like, 
- Which platform does this happen? 
- Is this happening in Simulator or happening on real device?

**Comment by aljaiban** [comment]
It is also happening to me right now. My device is Samsug Z Fold3 running Android 13. I appreciate if you have a quick fix for this.

**Comment by Senng** [comment]
It also happens to me. I am running it on a Pixel4 Android 13 emulator .

**Comment by MGohil** [comment]
I will check this issue soon and meanwhile if anyone of you can help identify the fix and raise the PR, I will be happy to approve and merge.

I don't have any Samsung device, but as @Senng mentioned its also happening in Pixel4 Android 13 emulator, this will help me. Thanks.

**Comment by MGohil** [comment]
This is an open issue from .NET Maui. I will check for work-around on this weekend. https://github.com/dotnet/maui/issues/5983

**Comment by asaleh-lab** [comment]
Hi, 
i thought it's meanwhile fixed in maui as it was since April 2022 :D In my case it happens on the following devices 
-Physical device Samsung Galaxy A32 with Android 13 
-Pixel 5 Emulator
I'd appreciate your suggestions 
Thanks and best regards!

**Comment by MGohil** [comment]
Closing this as this is not a PINView.MAUI issue but rather .net Maui issue where they have fixed in .net 8.0.
However, I have still applied a work-around in the sample project which you can do in your project too if the same issue is seen.
