### ISSUE TITLE
Add dash stroke

### ISSUE THREAD

**Issue by haideralifaizi** [MGohil/PINView.Maui#15]
Is there any way in this plugin to dash stroke and also change box radius. I check it but i have not found it. If, it has not, can you please add it?

**Comment by MGohil** [comment]
Hi @haideralifaizi 

Do you mean to show border around each boxes like this?
![image](https://github.com/user-attachments/assets/2ea7457d-925b-46dc-91b6-0bf1f3546991)

Unfortunately this control does not support this type of border, but I will try to provide this in some upcoming release.
Also, this control provides 3 fixed shapes Circle, Square, and RoundCorner but does not have option to change radius. May I know why this is required?

Thanks.

**Comment by haideralifaizi** [comment]
Yes, like that as you mention above.

**Comment by MGohil** [comment]
@haideralifaizi : I have added `BoxStrokeDashArray` and `BoxStrokeDashOffset` properties. You can update to V 1.0.3 to get this.
Thanks.

**Comment by haideralifaizi** [comment]
Thanks 👍
