### ISSUE TITLE
Feature Request: Bindable AutomationId Property for Each Digit in PINView for UI Testing

### ISSUE THREAD

**Issue by alpayclsr1** [MGohil/PINView.Maui#16]
I am currently using your PINView.Maui library for my project, and it's been very helpful—thank you for your work on it!

For UI automation testing, I need a way to assign unique identifiers to each digit in the PIN view. Could you please add a bindable AutomationId property for each individual digit? This would greatly assist in creating reliable UI tests by allowing us to target each digit field independently.

Thank you for considering this request, and I look forward to any updates

**Comment by MGohil** [comment]
Hi @alpayclsr1 

Those boxes are just UI representation of digits but those are not actual inputs. This control actually have 1 single `Entry` control behind the scene which holds all digits as a single string in one textbox.
May be I can provide `AutomationId` for that single `Entry` control if that works for you ?

**Comment by alpayclsr1** [comment]
Hi @MGohil  Yes, if you can provide the AutomationId for that single Entry control, it would be incredibly helpful. Thank you so much! I’d greatly appreciate it if you could add it in the next version.

**Comment by MGohil** [comment]
@alpayclsr1 : I have added `AutomationId` property in V 1.0.3

This control uses Hidden Entry behind the scene to hold PIN input value. To work with Automation, you have to set `AutomationId` of this PINView control, and it will internally set the `AutomationId` of this hidden Entry. 
Example: If you set `AutomationId` of `PINView` control as 'ConfirmPIN' then `AutomationId` of hidden Entry will be 'ConfirmPIN_PINView_Entry'. You can get the hidden Entry's `AutomationId` using `HiddenEntryAutomationId` property.
