### ISSUE TITLE
Feature Request: For dynamically changing of size

### ISSUE THREAD

**Issue by haideralifaizi** [MGohil/PINView.Maui#18]
I’ve encountered an issue with the default size of the indicator boxes, which is set to 50. When there are six or more items, it causes layout problems. Is it possible to implement a feature that adjusts the size dynamically, ensuring the indicators fit properly on all screen sizes?
Thank you for considering this request, and I look forward to any updates!

**Comment by ewerspej** [comment]
Indeed, one of the major issues with this control is that it relies on a HorizontalStackLayout. StackLayout are unrestrained and simply grow with their content. This means that the content can go out of view, depending on the screen width. It would be better if the control used some automatic sizing approach, e.g. using the assigned Width and dividing that by the number of boxes and taking the spacing into account. This could be done with a Grid and dynamic creation of columns. If the boxes are sized automatically when there isn't enough space, then the font size must also be automatically adjusted, which is a whole other issue.

**Comment by MGohil** [comment]
@haideralifaizi : As per what @ewerspej mentioned, this control uses the HorizontalStackLayout to contain the boxes. 
FYI, this control provides the property to set the BoxSize.
As a workaround, you can use this property to set different BoxSize per different screen sizes of devices which best fit for device size.

Ex: For smaller width devices, you can probably set to 35 or 40 and for bigger size device you can set 50 or 55. This will solve your issue.

![image](https://github.com/user-attachments/assets/1cbd74f2-f943-4e23-a779-331c6afbe242)

Thanks.

**Comment by haideralifaizi** [comment]
Thanks. But can you one more issue. That box stroke width and box size works fine in case of four pin. If, i change pin length to more than four, box stroke width and box size cause issues on remaining

**Comment by MGohil** [comment]
@haideralifaizi : Would you please paste some code for all property setting for PINView ? or Screenshot will help.

**Comment by MGohil** [comment]
@haideralifaizi I have identified above issue and fixed in V 1.0.3.

**Comment by haideralifaizi** [comment]
Thanks 👍
