### ISSUE TITLE
How to focus on appear?

### ISSUE THREAD

**Issue by Kiriakos41** [MGohil/PINView.Maui#19]
i want to show keyboard on appear on the page Pin.focus() dosent work!

**Comment by MGohil** [comment]
@Kiriakos41 : There is `pinView.FocusBox()` method. You can call this on MainThread with some delay and it will bring up the keyboard programatically.

`Dispatcher.DispatchDelayed(TimeSpan.FromMilliseconds(200), () => { pinView.FocusBox(); });`

Please let me know if this works, I will then close the bug.

Thanks.

**Comment by Kiriakos41** [comment]
Yep thank you is working now
