### ISSUE TITLE
Keyboard not dismissed automatically on Android

### ISSUE THREAD

**Issue by marcustindab** [MGohil/PINView.Maui#8]
Hi,

I've been playing around with your plugin on my android emulator and has noticed that the keyboard doesn't get dismissed automatically when the pin is entered. Only when I actively click on the "Complete" button. Maybe this is something you could take a look at?

All in all; great job with the plugin!

**Comment by apoorvadixit-ttc** [comment]
Same issue, AutoDissmissKeyboard does not remove the keyboard on Android. Any chance it could be looked at?

**Comment by apoorvadixit-ttc** [comment]
> Same issue, AutoDissmissKeyboard does not remove the keyboard on Android. Any chance it could be looked at?

Sorry, didnt realise but for Android do the following in MauiProgram.cs:
```
#if ANDROID
                .ConfigureMauiHandlers(handlers => handlers.AddHandler<Microsoft.Maui.Controls.Entry, PINView.Maui.Platforms.Android.Handlers.EntryHandler>())
#endif

```
This does the job for me.

**Comment by MGohil** [comment]
@apoorvadixit-ttc Thanks, yes we have to apply this to get this working.
