### ISSUE TITLE
Deleting a number in the middle of the pin

### ISSUE THREAD

**Issue by developer9969** [MGohil/PINView.Maui#9]
Hi there,
thank you for this control. 

if we have a PinView with a PinLength of 5 and I want to delete a pin in the middle I have to delete them all.

Is there a way to allow only deletion of a single pin?
many thanks

**Comment by MGohil** [comment]
@developer9969 

Thank you for your feedback.

Unfortunately "Deleting the character from anywhere in the middle" is not supported yet and it will be very tricky to do this, hence won't be available in near future.
